### PR TITLE
Cleanup of UI code related to effect controllers

### PR DESCRIPTION
**Pull request by ArXen42**
While working on #72  I've noticed that [UIControllerPopupWindow.cs](https://github.com/post-kerbin-mining-corporation/Waterfall/blob/master/Source/Waterfall/UI/UIControllerPopupWindow.cs) is a little messy: 574 LOC with a lot of duplicating boilerplate like ```if (ctrlType == "atmosphere_depth") ...```, so I tried to improve this as much as possible.

Main changes:

- Extracted duplications of strings like `atmosphere_depth` into string constants. Please check that I understood things correctly in #94 where I described issue with "name" and "linkedTo" default values.
- Extracted individual controllers UI logic into separate classes, all derived from new ```IEffectControllerUIOptions``` interface. This should both make things more readable and less error prone. For example, that way I've noticed that for ```GimbalController``` values weren't passed from controller to UI when entering "edit" screen.
- Fixed a few occurences of  empty UI fields when adding new controller (for example ramp up values). I wish we had fully fledged MVVM framework for KSP so this wouldn't happen in the first place :)
- Controller type selection grid now shows "pretty" names instead of identifiers from code (screenshot included).
image

Now to add new controller type only two files are needed - controller itself and it's UI logic class. New controller type will be automatically picked up and shown in UI.

If you won't like some of these fixes I can revert or rework them of course. If everything is ok I will base #72 on this branch.

A few more suggestions I can also implement if you agree with them:

1. When pressing "add new controller" - reset UI settings for new controller to default instead of showing whatever was left from previous "edit" or "add new" operation and set controller name to selected controller type name instead of default "controller". It is now simple because all this UI state is separated for each controller instead of being part of ```UIControllerPopupWindow```.
2. Setup ```.editorconfig``` and/or ```.DotSettings``` for automatic code cleanup. There are lots of code style inconsistencies like missing explicit modifiers, ```String.Format``` usage instead of interpolation (and some other newer C# features could be used), braces placement, [members ordering](https://github.com/ArXen42/ReSharper-File-Layouts), spaces, aligning, etc, etc which can be automatically normalized by IDE. I have most of this setup in other projects anyway, so I can add config and apply formatting if you want (without drastically changing existing codestyle of course).
3. Eliminate build warnings (some unused variables mostly) and setup "Treat all warnings as errors" to keep code clean.
4. Switch build target from .NET Framework 4.5 to .NET Framework 4.5.2. Microsoft [no longer allows to download 4.5 SDK](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks) and switching to 4.5.2 doesn't seem to affect anything for me. Folks from RO use 4.7.2 even.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Thanks for doing this, the code all related to that was a real dumpster fire. I will start reviewing this today, my main concern is maintaining compatibility with existing effects.

**Comment by ChrisAdderley** [comment]
I have looked at this an overall it looks great, however there's something bugging me in the set of controller name/linkedto/etc that could use clarification.

In the old model, `name` and `linkedTo` were the only controller identifiers, with `name` a user-settable mutable name for the controller and `linkedTo` a const that was used for loading the controller and saving it. There was no need for matching between these values because there was never a guarantee that a user wouldn't change it, so I didn't bother aligning it.  

This PR now has `name`, `Name`, `displayName` and `linkedTo` present which are hard to grok to a reader. Suggest we change variable naming up a bit to clarify responsability (note that I'm not married to these names, happy to consider others).
- `name`: defines user-defined mutable name
- `displayName`: defines constant friendly UI name
- `controllerType`: defines the type of controller (really only for loading and saving at this point

The gotcha is that we still need to parse old controllers of this form so should be careful there not to break the past:
```
{
  name = userName   // defines name
  linkedTo = theControllerType //  defines controllerType
}
```

**Comment by ArXen42** [comment]
Yes, I was actually about to push another commit which renamed `Name` to `ControllerTypeId` for more clarity. Added new commit with this rename and a few minor simplifications.

By the way, after closer look I've noticed that assigning `name` in the default constructor to anything seems to be unnecessary. Regardless of whether controller was deserialized from `ConfigNode` or created from UI, it's name is always reassigned to either user-defined name or name from config (and, just in case, it is "unnamedController" by default anyway). Included this in separate commit.

**Comment by ArXen42** [comment]
I just re-read your comment and realized that there is still some confusion left after rename. Pushed another change with some improvements, names are now like this:

1. `name` - same as before
2. `ControllerTypeId` - static const representing old `linkedTo` value
3. `TypeId` same thing but instance member (renamed old linkedTo and made into read-only abstract property to enforce implementation contract).

String `linkedTo` is now only used as keyword to search and save in config nodes.

Hopefully now it is as clear as possible, though I can change names to something else if you want. Not sure what naming conventions are in KSP/Unity world.

I wish we could get rid of duplication between `ControllerTypeId` and `TypeId` or maybe eliminate them completely, using simply type names instead. I feel like this would probably be much simpler and cleaner solution, but some effort will be needed to maintain backward compatibility. Maybe I'll experiment with this tomorrow though.

**Comment by ArXen42** [comment]
So in https://github.com/post-kerbin-mining-corporation/Waterfall/pull/95/commits/116b46c713796620da0815922cc4087969d55dd9 I've removed `linkedTo` completely. So instead of writing something like `controller.linkedTo` or `ThrottleController.ControllerTypeId`, we now use `controller.GetType().Name` and `nameof(ThrottleController)` respectively, though it is only needed in a few places.

Basically, given that `linkedTo` was already in 1-to-1 relationship with controller type, why would we need it at all if we could just use name of the type? So I've removed it completely and it seems to work fine.
For backward compatibility of course we maintain table in `EffectControllersMetadata` like this:
```cs
/// <summary>
///     These were used before field "linkedTo" was replaced by using controller type names for serialization.
/// </summary>
public static readonly IReadOnlyDictionary<string, string> LegacyControllerTypeIds = new Dictionary<string, string>
{
  ["atmosphere_density"] = nameof(AtmosphereDensityController),
  ["custom"]             = nameof(CustomController),
  ["gimbal"]             = nameof(GimbalController),
  ["light"]              = nameof(LightController),
  ["mach"]               = nameof(MachController),
  ["random"]             = nameof(RandomnessController),
  ["rcs"]                = nameof(RCSController),
  ["throttle"]           = nameof(ThrottleController),
  ["thrust"]             = nameof(ThrustController),
};
```

which is checked when loading controllers from config. Otherwise, for new configs, simply type names are used. Example of new generated config:
<details>
  <summary>Config example</summary>

    ```cs
    MODULE
    {
    	name = ModuleWaterfallFX
    	moduleID = RCSPodFX
    	CONTROLLER
    	{
    		name = atmosphereDepth
    		linkedTo = AtmosphereDensityController
    	}
    	CONTROLLER
    	{
    		name = rcs
    		linkedTo = RCSController
    		responseRateUp = 100
    		responseRateDown = 100
    		thrusterTransformName = 
    	}
    	CONTROLLER
    	{
    		name = R1
    		linkedTo = RandomnessController
    		noiseType = perlin
    		scale = 1
    		minimum = 0
    		speed = 12
    		seed = 1
    	}
    	CONTROLLER
    	{
    		name = controller
    		linkedTo = MachController
    	}
    	TEMPLATE
    	{
    		templateName = stock-rcs-jet-2
    		overrideParentTransform = thrustTransform
    		scale = 1,1,1
    		rotation = 0,0,180
    		position = 0,0.0280000009,0
    	}
    }
    ```

</details>

**Comment by ChrisAdderley** [comment]
This is better. Sorry I'm kinda retired from modding so it's slow for me to get time to review.

IMO the absolute best way to do this (and more consistent with KSP's confignode patterns) is to use named controller nodes, which effectively eliminates the need to save a parameter for the kids defining the linkage e.g. 
```
MACHCONTROLLER
{
  controllerID = userName // note this should not be name if we can avoid it
  // Mach controller specific params
  
} 
```

This has seemed like a lot of work to get to though while maintaining compatibility when I've looked at it in the past. The solution you proposed already makes concessions for compat though, so maybe we can consider going all the way to a best practices thing?

**Comment by ChrisAdderley** [comment]
This is better. Sorry I'm kinda retired from modding so it's slow for me to get time to review.

IMO the absolute best way to do this (and more consistent with KSP's confignode patterns) is to use named controller nodes, which effectively eliminates the need to save a parameter for the kids defining the linkage e.g. 
```
MACHCONTROLLER
{
  controllerID = userName // note this should not be name if we can avoid it
  // Mach controller specific params
  
} 
```

This has seemed like a lot of work to get to though while maintaining compatibility when I've looked at it in the past. The solution you proposed already makes concessions for compat though, so maybe we can consider going all the way to a best practices thing?

**Comment by ChrisAdderley** [comment]
This is better. Sorry I'm kinda retired from modding so it's slow for me to get time to review.

IMO the absolute best way to do this (and more consistent with KSP's confignode patterns) is to use named controller nodes, which effectively eliminates the need to save a parameter for the kids defining the linkage e.g. 
```
MACHCONTROLLER
{
  controllerID = userName // note this should not be name if we can avoid it
  // Mach controller specific params
  
} 
```

This has seemed like a lot of work to get to though while maintaining compatibility when I've looked at it in the past. The solution you proposed already makes concessions for compat though, so maybe we can consider going all the way to a best practices thing?

**Comment by ArXen42** [comment]
Done (54d6648). Backward compatibility handling is a little more complex now but nothing too bad. Example generated config:
```ini
MODULE
{
	name = ModuleWaterfallFX
	moduleID = MastodonFX
	ATMOSPHEREDENSITYCONTROLLER
	{
		name = atmosphereDepth
	}
	THROTTLECONTROLLER
	{
		name = throttle
		engineID = basicEngine
		responseRateUp = 0.0299999993
		responseRateDown = 0.200000003
	}
	ENGINEEVENTCONTROLLER
	{
		name = test-controller
		eventDuration = 2
		eventName = ignition
		eventCurve
		{
			key = 0 0 10 10
			key = 0.1 1 4.444445 4.444445
			key = 1 0 -1.111111 -1.111111
		}
	}
	TEMPLATE
	{
		templateName = waterfall-kerolox-lower-5-SWE
		overrideParentTransform = thrustTransform
		scale = 3.06999993,3.06999993,3.06999993
		rotation = 0,0,0
		position = 0,0,-0.159999996
	}
	TEMPLATE
	{
		templateName = stock-kerolox-core
		overrideParentTransform = thrustTransform
		scale = 3.06500006,3.06500006,2.70000005
		rotation = 0,0,0
		position = 0,0,-0.155000001
	}
}

```

### Few other changes

1. I've also bumped .NET to 4.5.2 (so VS 2022 users like me won't have to search .NET 4.5 to compile project or change locally to 4.5.2 every time) and checked-in updated dll. In my understanding this shouldn't break anything.

2. In the last commit I've applied automatic code style file. I happen to have licensed JB Rider, so added my usual code style files and ran automatic cleanup. This is highly opinionated topic, so if you don't like some or all of these changes I can revert/adjust them of course. Change list is long but purely visual, nothing functionally changed, just made everything follow the same formatting/stylistic rules.

**Comment by ArXen42** [comment]
I somehow missed your note regarding ```name```, will see if I can make another change to avoid it.
However, I'm not completely sure why having ```name``` field is bad, because of some kind of conflict with internal `ConfigNode` logic or something else?

**Comment by ChrisAdderley** [comment]
It's probably not that important. It helps with ModuleManager targeting but most of the time we don't expect players to patch WF nodes anyways.

I will review changes tonight.

**Comment by ChrisAdderley** [comment]
Ok I'm happy at this point. Are you good for this to get merged now?
(thanks for all of this btw, save me a lot of cleanup I was going to have to do eventually)

**Comment by ArXen42** [comment]
Great! I am almost ready to push #72 after merge too, but that would be just new controller type.

**Comment by ArXen42** [comment]
Added little rename change - changed name of `CustomController` to `CustomPushController`, given that there will be another `CustomPullController` added in separate PR. So their config nodes will be `CUSTOMPUSHCONTROLLER` and `CUSTOMPULLCONTROLLER` respectively.

**Comment by ChrisAdderley** [comment]
Pulled in. Need to do some regression testing and I'm working on improving some other UX right now but will do a release once that is done.

**Pull request merged**
